language: node_js

node_js:
- 9

install:
- yarn

cache:
  yarn: true
  directories:
  - node_modules

script:
- yarn build

deploy:
- provider: surge
  project: "./build"
  domain: pp9-scraper-fun.surge.sh
  skip_cleanup: true
  on:
    branch: master
    tags: true

notifications:
  email: false
  slack:
    secure: cEBdbS8nVFdSvZssNEy0LTtyKs3E2aRM7lC9JjtEu029AM7WV+FVMMOGDz1fXuQIy3/X35rd0U8K2KHbDXxVOoT4TcMgDTDwRhc/kHsRFAHEG1MK6l+XvBYX/ta3bCg+w6q9a5z/eppLxWJH1D9vIn0eSGO+9rlTh+X3FeANjOCI/5huS6Ssf31GeVaHi6ZrUT0ZtIaP7DV21YPDb5r9hkyEpJpIucPPU3GToqc/MzEWryrWQtWmsqxvFa6L1/2n9Yv4ZsUI0G8v9icqvHFP4D76GqzyO3tGP1fJKGdv29mrAoI52A2pl2KkgURO/3PxktvOaeQ8Ir3YFEsJfg/MtaSyEU1UtKYKTKR1g0b4FfE5CvQ13RMRQ5Owg5S92nVN7jdVsIKNTlQMOAoz4LP1qLkqbXj0TSlOVcL5vXFQydmxhr0C4PPHVe4u9m8qRNKLtmjD1O3YN5WDaWxTFkTnXgdXld0Xtp9RZR3keaKyBPGtRuQTg3Bwn9Vfhwst+35XXeUfGcLrEiRuiFsU27ItNDy/NbyYvYSHieLwXSYGV2YBSe8xpYZ85RGsC+dTrS0lxz27MqJEVy7l2WgOGb3Aa86eALuEWPzcC3i5g0rIBNIG4pL1A7AI3BeFPxVBeHlE7VtI+JJb3ahQ/VvTF/XC0O1kuvItxiLv3MIcpI924m4=
